"""Script to generate ground_truth.csv and candidate_standards.csv for human review."""

import csv

ground_truth_rows = [
    {
        "tender_id": "T001",
        "requirement_id": "T001-R002",
        "requirement_text": "replacement of damaged pipelines by Hubless",
        "category": "material",
        "source_page": 1,
        "explicit_standard": "",
        "applicable_standard": "IS 15905 : 2011; IS 1239 (Part 1) : 2004",
        "standard_title": "Cast Iron Hubless Pipes and Fittings for Waste Water and Ventilation Systems; Steel Tubes, Tubulars and Other Wrought Steel Fittings",
        "standard_status": "Active",
        "verification_outcome": "STANDARD_MISSING",
        "verification_method": "BIS_CATALOGUE",
        "evidence_source": "BIS Catalogue / CED 53 & CED 54",
        "evidence_reference": "IS 15905:2011 Clause 1 Scope; IS 1239 (Part 1):2004 Clause 1 Scope",
        "evidence_snippet": "IS 15905 specifies material, dimensions, coating, and test requirements for hubless cast iron pipes used in wastewater systems without socket joints.",
        "reasoning": "The tender specifies replacement of toilet drainage piping using hubless pipes and GI pipes. IS 15905 is the definitive Indian Standard for hubless cast iron soil/waste pipes, and IS 1239 covers GI steel tubes.",
        "confidence": "High",
        "human_verified": "FALSE",
        "reviewer_notes": "Hubless cast iron pipes are connected using mechanical couplings. Traditional socketed CI pipes under IS 1729 are rejected because the tender explicitly mandates hubless."
    },
    {
        "tender_id": "T001",
        "requirement_id": "T001-R003",
        "requirement_text": "wall tiles",
        "category": "material",
        "source_page": 1,
        "explicit_standard": "",
        "applicable_standard": "IS 15622 : 2017",
        "standard_title": "Pressed Ceramic Tiles - Specification (First Revision)",
        "standard_status": "Active",
        "verification_outcome": "STANDARD_MISSING",
        "verification_method": "BIS_CATALOGUE",
        "evidence_source": "BIS Catalogue / Ministry of Commerce & Industry (Ceramic Tiles QCO 2020)",
        "evidence_reference": "IS 15622:2017 Scope Clause 1",
        "evidence_snippet": "IS 15622 covers requirements for pressed ceramic tiles for floor and wall finishes (water absorption groups B Ia, B Ib, B IIa, B IIb, and B III). Mandatory ISI Mark under Quality Control Order.",
        "reasoning": "The tender requires replacement of toilet wall and floor tiles. IS 15622 is the umbrella mandatory Indian Standard governing all pressed ceramic, glazed, and vitrified tiles for interior wall and floor finishes.",
        "confidence": "High",
        "human_verified": "FALSE",
        "reviewer_notes": "Superseded earlier standards IS 13753 and IS 13755. Mandatory certification under Ceramic Tiles QCO."
    },
    {
        "tender_id": "T001",
        "requirement_id": "T001-R004",
        "requirement_text": "upgradation of all sanitary fittings at AGL Department in Main School Building at IIT ISM Dhanbad",
        "category": "product_equipment",
        "source_page": 1,
        "explicit_standard": "",
        "applicable_standard": "IS 2556 (Part 1 to 17); IS 781 : 1984; IS 774 : 2021",
        "standard_title": "Vitreous sanitary appliances (vitreous china); Cast copper alloy screw-down bib taps and stop valves; Flushing cisterns for water closets and urinals",
        "standard_status": "Active",
        "verification_outcome": "STANDARD_MISSING",
        "verification_method": "BIS_CATALOGUE",
        "evidence_source": "BIS Catalogue / CED 3 (Sanitary Installation)",
        "evidence_reference": "IS 2556 (Parts 1, 2, 4); IS 781 Clause 1; IS 774 Clause 1",
        "evidence_snippet": "IS 2556 governs vitreous china fixtures (water closets, wash basins, urinals). IS 781 governs bib taps and stop valves. IS 774 specifies flushing cisterns.",
        "reasoning": "Upgradation of institutional toilet sanitary fittings encompasses porcelain appliances (IS 2556), water supply bib taps/valves (IS 781), and flushing cisterns (IS 774). Multiple standards co-apply.",
        "confidence": "High",
        "human_verified": "FALSE",
        "reviewer_notes": "Tender aggregates sanitaryware under a single renovation title. CPWD Specifications Volume 2 Section 17 mandate these three core standards."
    },
    {
        "tender_id": "T002",
        "requirement_id": "T002-R002",
        "requirement_text": "Valve Replacement",
        "category": "material",
        "source_page": 1,
        "explicit_standard": "",
        "applicable_standard": "",
        "standard_title": "",
        "standard_status": "",
        "verification_outcome": "NEEDS_EXPERT_VERIFICATION",
        "verification_method": "UNVERIFIED",
        "evidence_source": "Heavy Water Board Tender Notice HWBFV/21/2026-27/TS-733",
        "evidence_reference": "Page 1, Work Description: Mechanical Maintenance Works including Pumps, Valve Replacement",
        "evidence_snippet": "Tender notice summary mentions generic Valve Replacement in Heavy Water Plant chemical/mechanical services without line pressure, temperature, or fluid media details.",
        "reasoning": "While IS 778 (copper alloy valves), IS 14846 (sluice valves), and IS 13095 (butterfly valves) exist in the BIS catalogue, assigning a specific standard without the detailed piping schedule/BOQ would be speculative.",
        "confidence": "Low",
        "human_verified": "FALSE",
        "reviewer_notes": "Requires inspection of the detailed tender annexure (HWBFV/21/2026-27 technical schedule) to confirm whether service is cooling water (IS 14846/IS 778) or process steam/chemical (ASME/IS bolted steel gate valves)."
    },
    {
        "tender_id": "T002",
        "requirement_id": "T002-R003",
        "requirement_text": "Flange Joint Maintenance",
        "category": "installation_execution",
        "source_page": 1,
        "explicit_standard": "",
        "applicable_standard": "IS 6392 : 1971; IS 2712 : 2020",
        "standard_title": "Steel Pipe Flanges; Compressed Asbestos/Non-Asbestos Fiber Jointing Sheets - Specification",
        "standard_status": "Active",
        "verification_outcome": "STANDARD_MISSING",
        "verification_method": "BIS_CATALOGUE",
        "evidence_source": "BIS Catalogue / MED 17",
        "evidence_reference": "IS 6392:1971 Scope Clause 1; IS 2712:2020 Clause 1",
        "evidence_snippet": "IS 6392 specifies dimensional, machining and tolerance requirements for steel pipe flanges. IS 2712 governs sealing gasket sheets for flanged joints.",
        "reasoning": "Mechanical maintenance of pipe flange joints in an industrial plant requires compliance with IS 6392 for flange facings/bolt holes and IS 2712 for gasket replacement jointing materials.",
        "confidence": "High",
        "human_verified": "FALSE",
        "reviewer_notes": "Flanges in chemical/process piping follow standard rating classes (150, 300, 600) aligned with IS 6392 / ASME B16.5."
    },
    {
        "tender_id": "T003",
        "requirement_id": "T003-R001",
        "requirement_text": "Replacement / repair of distribution boards and defective lights at various locations in main sports stadium",
        "category": "material",
        "source_page": 1,
        "explicit_standard": "",
        "applicable_standard": "IS/IEC 61439-3 : 2012; IS 10322 (Part 5 / Sec 5) : 2013",
        "standard_title": "Low-voltage switchgear and controlgear assemblies - Part 3: Distribution boards (DBO); Luminaires - Part 5 Particular Requirements - Section 5 Floodlights",
        "standard_status": "Active",
        "verification_outcome": "STANDARD_MISSING",
        "verification_method": "BIS_CATALOGUE",
        "evidence_source": "BIS Catalogue / ETD 7 (Switchgear) & ETD 24 (Illumination)",
        "evidence_reference": "IS/IEC 61439-3 Clause 1; IS 10322 (Part 5/Sec 5) Clause 1",
        "evidence_snippet": "IS/IEC 61439-3 specifies distribution boards for ordinary person operation. IS 10322 (Part 5/Sec 5) covers floodlights designed for stadium and outdoor sports illumination.",
        "reasoning": "Stadium electrical maintenance involves two distinct equipment classes: power distribution boards (IS/IEC 61439-3) and sports stadium floodlighting luminaires (IS 10322 Part 5 Sec 5). Both standards apply.",
        "confidence": "High",
        "human_verified": "FALSE",
        "reviewer_notes": "IS/IEC 61439-3 superseded the older IS 8623 (Part 3) : 1993."
    },
    {
        "tender_id": "T004",
        "requirement_id": "T004-R002",
        "requirement_text": "power cables from outside of electrical room to AMF room",
        "category": "material",
        "source_page": 1,
        "explicit_standard": "",
        "applicable_standard": "IS 7098 (Part 1) : 1988; IS 1255 : 1983",
        "standard_title": "Crosslinked polyethylene insulated thermoplastic sheathed cables - Part 1: For working voltage up to and including 1100 V; Code of practice for installation and maintenance of power cables",
        "standard_status": "Active",
        "verification_outcome": "STANDARD_MISSING",
        "verification_method": "BIS_CATALOGUE",
        "evidence_source": "BIS Catalogue / ETD 9 / Electrical Cables QCO",
        "evidence_reference": "IS 7098 (Part 1) Clause 1; IS 1255 Clause 1",
        "evidence_snippet": "IS 7098 (Part 1) specifies armored XLPE power cables up to 1.1 kV. IS 1255 provides the national code of practice for laying, trenching and terminating power cables.",
        "reasoning": "Connecting substation electrical rooms to Auto Mains Failure (AMF) generator changeover rooms requires heavy-duty XLPE LT armored power cables (IS 7098 Part 1) and proper cable laying practice (IS 1255).",
        "confidence": "High",
        "human_verified": "FALSE",
        "reviewer_notes": "Mandatory ISI Mark under Cables Quality Control Order. PVC insulated cables under IS 1554 (Part 1) are an acceptable alternative, but XLPE is CPWD standard."
    },
    {
        "tender_id": "T004",
        "requirement_id": "T004-R005",
        "requirement_text": "Dismantling,Shifting and reinstallation of feeder pillar, power",
        "category": "product_equipment",
        "source_page": 1,
        "explicit_standard": "",
        "applicable_standard": "IS 5039 : 1983; IS/IEC 61439-5 : 2014",
        "standard_title": "Distribution pillars for voltages not exceeding 1000 V AC and 1200 V DC - Specification; Low-voltage switchgear and controlgear assemblies - Part 5",
        "standard_status": "Active",
        "verification_outcome": "STANDARD_MISSING",
        "verification_method": "BIS_CATALOGUE",
        "evidence_source": "BIS Catalogue / ETD 7",
        "evidence_reference": "IS 5039:1983 Clause 1 Scope",
        "evidence_snippet": "IS 5039 specifies design, enclosure ingress protection, and busbar performance for outdoor/indoor low voltage distribution pillars (feeder pillars).",
        "reasoning": "The tender specifically mandates shifting and reinstalling an electrical feeder pillar. IS 5039 is the dedicated Indian Standard for feeder distribution pillars.",
        "confidence": "High",
        "human_verified": "FALSE",
        "reviewer_notes": "Ingress protection should conform to IP 55 under IS/IEC 60529 for outdoor pillars."
    },
    {
        "tender_id": "T005",
        "requirement_id": "T005-R001",
        "requirement_text": "Cable connection of DG Set in Newly constructed building of the Dept. of Molecular , Human Genetics",
        "category": "material",
        "source_page": 1,
        "explicit_standard": "",
        "applicable_standard": "IS 3043 : 2018; IS 7098 (Part 1) : 1988; IS 1293 : 2019",
        "standard_title": "Code of practice for earthing; Crosslinked polyethylene insulated cables; Plugs and socket-outlets of rated voltage up to 250 V",
        "standard_status": "Active",
        "verification_outcome": "STANDARD_MISSING",
        "verification_method": "BIS_CATALOGUE",
        "evidence_source": "BIS Catalogue / ETD 20 (Earthing) & ETD 9 (Cables)",
        "evidence_reference": "IS 3043:2018 Clause 28 (Earthing of generating plants); IS 1293 Scope Clause 1",
        "evidence_snippet": "IS 3043 mandates independent neutral earthing and body earthing for DG sets. IS 7098 (Part 1) specifies the power cables. IS 1293 covers power sockets replaced in the room.",
        "reasoning": "Connecting a Diesel Generator set requires dedicated generator earthing (IS 3043), high-current XLPE cables (IS 7098 Part 1), and power sockets (IS 1293) specified in the tender title.",
        "confidence": "High",
        "human_verified": "FALSE",
        "reviewer_notes": "Central Electricity Authority (CEA) Regulations 2010 mandate strict compliance with IS 3043 for generating units."
    },
    {
        "tender_id": "T006",
        "requirement_id": "T006-R001",
        "requirement_text": "UPVC Partition Wall Work for Conversion of Seafood Authentication Laboratory into Conventional Microbiology Laboratory",
        "category": "material",
        "source_page": 1,
        "explicit_standard": "",
        "applicable_standard": "IS 16088 : 2016",
        "standard_title": "Unplasticized Polyvinyl Chloride (uPVC) Profiles for the Fabrication of Windows and Doors - Specification",
        "standard_status": "Active",
        "verification_outcome": "STANDARD_MISSING",
        "verification_method": "BIS_CATALOGUE",
        "evidence_source": "BIS Catalogue / CED 29 (Plastic Building Components)",
        "evidence_reference": "IS 16088:2016 Scope Clause 1",
        "evidence_snippet": "IS 16088 specifies raw materials, mechanical properties, weather resistance and wall thickness for unplasticized PVC profiles used in architectural partitions, windows and frames.",
        "reasoning": "The tender requires fabrication of internal partition walls using UPVC profiles for a cleanroom/microbiology laboratory. IS 16088 is the Bureau of Indian Standards specification for structural UPVC profile systems.",
        "confidence": "High",
        "human_verified": "FALSE",
        "reviewer_notes": "Prefinished UPVC multi-chamber hollow profiles are standard in wet/sterile marine laboratory partitions."
    },
    {
        "tender_id": "T007",
        "requirement_id": "T007-R003",
        "requirement_text": "Low-Oil Food Outlet on BOT",
        "category": "general_specification",
        "source_page": 1,
        "explicit_standard": "",
        "applicable_standard": "IS 2491 : 2013; IS 15000 : 2013",
        "standard_title": "Food Hygiene - General Principles - Code of Practice (Second Revision); Food safety management systems - Requirements",
        "standard_status": "Active",
        "verification_outcome": "STANDARD_MISSING",
        "verification_method": "BIS_CATALOGUE",
        "evidence_source": "BIS Catalogue / FAD 15 (Food Hygiene, Safety Management)",
        "evidence_reference": "IS 2491:2013 Clause 1 Scope",
        "evidence_snippet": "IS 2491 establishes general principles of food hygiene for premises design, equipment, food operations, sanitation and personal hygiene in catering outlets.",
        "reasoning": "Operating a commercial catering food outlet on a university campus requires strict adherence to national food hygiene codes (IS 2491) and Food Safety and Standards (FSSAI) hygiene guidelines.",
        "confidence": "High",
        "human_verified": "FALSE",
        "reviewer_notes": "IS 2491 is the Indian Standard equivalent of Codex Alimentarius general principles of food hygiene."
    },
    {
        "tender_id": "T009",
        "requirement_id": "T009-R001",
        "requirement_text": "Annual Repairs and Maintenance Contract for electrical and mechanical services alongwith requisite materials at FSD",
        "category": "installation_execution",
        "source_page": 1,
        "explicit_standard": "",
        "applicable_standard": "SP 30 : 2023; IS 732 : 2019",
        "standard_title": "National Electrical Code Of India 2023; Code of practice for electrical wiring installations (Fourth Revision)",
        "standard_status": "Active",
        "verification_outcome": "STANDARD_MISSING",
        "verification_method": "BIS_METADATA",
        "evidence_source": "data/standards/standards.xlsx / ETD 20",
        "evidence_reference": "SP 30:2023 Section 3 (Storage and Warehousing Facilities); IS 732 Clause 6",
        "evidence_snippet": "SP 30 provides national guidelines for electrical installation, inspection, and maintenance in food storage depots (FSD). IS 732 governs periodic testing of wiring systems.",
        "reasoning": "FCI food storage depots have grain dust safety hazards. Electrical maintenance in storage facilities must comply with the National Electrical Code (SP 30) and wiring maintenance code (IS 732).",
        "confidence": "High",
        "human_verified": "FALSE",
        "reviewer_notes": "SP 30:2023 was recently reaffirmed/updated as the master electrical code of India."
    },
    {
        "tender_id": "T010",
        "requirement_id": "T010-R001",
        "requirement_text": "Sewerage Pipeline works from Collection Chamber to STP 9/4/26",
        "category": "material",
        "source_page": 1,
        "explicit_standard": "",
        "applicable_standard": "IS 458 : 2021; IS 783 : 1985; IS 14333 : 1996",
        "standard_title": "Precast Concrete Pipes (with and without Reinforcement) - Specification; Code of Practice for Laying of Concrete Pipes; High density polyethylene pipes for sewerage",
        "standard_status": "Active",
        "verification_outcome": "STANDARD_MISSING",
        "verification_method": "BIS_METADATA",
        "evidence_source": "data/standards/standards.xlsx / CED 53",
        "evidence_reference": "IS 458:2021 Scope Clause 1; IS 783:1985 Scope Clause 1",
        "evidence_snippet": "IS 458 specifies RCC NP2/NP3 precast concrete pipes for gravity sewerage. IS 783 provides civil laying, trenching and jointing practice. Mandatory ISI Mark under Precast Concrete Pipes QCO.",
        "reasoning": "Conveying raw sewage from a collection chamber to a Sewage Treatment Plant (STP) requires underground precast concrete pipes (IS 458) or HDPE pipes (IS 14333) laid under IS 783.",
        "confidence": "High",
        "human_verified": "FALSE",
        "reviewer_notes": "Both IS 458 and IS 783 are in our active standards repository. Reinforced concrete pipes are mandatory ISI certified."
    },
    {
        "tender_id": "T011",
        "requirement_id": "T011-R001",
        "requirement_text": "Providing and laying underground cable for STP for main supply of electricity under CEDCO BSF Bangalore",
        "category": "material",
        "source_page": 1,
        "explicit_standard": "",
        "applicable_standard": "IS 7098 (Part 1) : 1988; IS 1255 : 1983",
        "standard_title": "Crosslinked polyethylene insulated thermoplastic sheathed cables - Part 1: For working voltage up to and including 1100 V; Code of practice for installation and maintenance of power cables",
        "standard_status": "Active",
        "verification_outcome": "STANDARD_MISSING",
        "verification_method": "BIS_CATALOGUE",
        "evidence_source": "BIS Catalogue / ETD 9 / Cables QCO",
        "evidence_reference": "IS 7098 (Part 1) Clause 1; IS 1255 Section 6",
        "evidence_snippet": "IS 7098 (Part 1) specifies underground armored XLPE power cables up to 1100 V. IS 1255 specifies underground trench dimensions, bedding sand, warning tiles, and cable pulling tension.",
        "reasoning": "The tender explicitly demands providing and laying underground cable for STP main supply. The cable product is governed by IS 7098 Part 1 and underground laying is governed by IS 1255.",
        "confidence": "High",
        "human_verified": "FALSE",
        "reviewer_notes": "Armoured cable (strip or wire armour) is mandatory for direct burial underground power applications to protect against mechanical injury."
    },
    {
        "tender_id": "T012",
        "requirement_id": "T012-R002",
        "requirement_text": "Plaster Repairing",
        "category": "installation_execution",
        "source_page": 1,
        "explicit_standard": "",
        "applicable_standard": "IS 1661 : 1972; IS 269 : 2015",
        "standard_title": "Code of practice for application of cement and cement-lime plaster finishes; Ordinary Portland Cement - Specification",
        "standard_status": "Active",
        "verification_outcome": "STANDARD_MISSING",
        "verification_method": "BIS_CATALOGUE",
        "evidence_source": "BIS Catalogue / data/standards/standards.xlsx / CED 4 & CED 2",
        "evidence_reference": "IS 1661:1972 Clause 1 Scope; IS 269:2015 Clause 1",
        "evidence_snippet": "IS 1661 specifies mix proportions (1:3, 1:4), background surface preparation, application in coats, and curing period for cement plastering. IS 269 governs the OPC cement binder.",
        "reasoning": "Civil repair of damaged wall plaster in a storm water pump room requires adherence to the cement plaster code of practice (IS 1661) and quality cement specification (IS 269).",
        "confidence": "High",
        "human_verified": "FALSE",
        "reviewer_notes": "CPWD Civil Specifications Section 11 directly mandates IS 1661 for all plastering works."
    },
    {
        "tender_id": "T012",
        "requirement_id": "T012-R003",
        "requirement_text": "Plumbing Fittings",
        "category": "product_equipment",
        "source_page": 1,
        "explicit_standard": "",
        "applicable_standard": "IS 1239 (Part 2) : 1992; IS 778 : 1984",
        "standard_title": "Mild Steel Tubulars and Other Wrought Steel Pipe Fittings; Copper alloy gate, globe and check valves for water works purposes",
        "standard_status": "Active",
        "verification_outcome": "STANDARD_MISSING",
        "verification_method": "BIS_CATALOGUE",
        "evidence_source": "BIS Catalogue / CED 54 & CED 3",
        "evidence_reference": "IS 1239 (Part 2) Clause 1; IS 778 Clause 1",
        "evidence_snippet": "IS 1239 (Part 2) governs steel and malleable iron pipe fittings (tees, elbows, unions). IS 778 governs brass/bronze control valves in plumbing networks.",
        "reasoning": "Plumbing fittings in a storm water pump room encompass threaded steel/wrought pipe fittings (IS 1239 Part 2) and copper-alloy isolation/check valves (IS 778).",
        "confidence": "High",
        "human_verified": "FALSE",
        "reviewer_notes": "Covered under the general water supply handbook SP 57 in our active repository."
    },
    {
        "tender_id": "T013",
        "requirement_id": "T013-R002",
        "requirement_text": "SITC of VFD water pump panel",
        "category": "product_equipment",
        "source_page": 1,
        "explicit_standard": "",
        "applicable_standard": "IS/IEC 61800-2 : 2015; IS/IEC 61439-2 : 2011",
        "standard_title": "Adjustable speed electrical power drive systems - Part 2: General requirements; Low-voltage switchgear and controlgear assemblies - Part 2",
        "standard_status": "Active",
        "verification_outcome": "STANDARD_MISSING",
        "verification_method": "BIS_CATALOGUE",
        "evidence_source": "BIS Catalogue / ETD 22 & ETD 7",
        "evidence_reference": "IS/IEC 61800-2 Clause 1; IS/IEC 61439-2 Clause 1",
        "evidence_snippet": "IS/IEC 61800-2 specifies ratings, performance, and THD harmonic limits for variable frequency drives. IS/IEC 61439-2 covers the motor control center (MCC) enclosure assembly.",
        "reasoning": "Supply, installation, testing and commissioning (SITC) of a Variable Frequency Drive pump control panel requires adherence to drive equipment standards (IS/IEC 61800-2) and switchgear panel assembly standards (IS/IEC 61439-2).",
        "confidence": "High",
        "human_verified": "FALSE",
        "reviewer_notes": "Hospital water booster pumps use VFDs for constant water pressure control and energy efficiency."
    },
    {
        "tender_id": "T013",
        "requirement_id": "T013-R003",
        "requirement_text": "Insulation work",
        "category": "material",
        "source_page": 1,
        "explicit_standard": "",
        "applicable_standard": "IS 14164 : 2008; IS 8183 : 1993",
        "standard_title": "Industrial application and finishing of thermal insulation materials - Code of practice; Bonded mineral wool - Specification",
        "standard_status": "Active",
        "verification_outcome": "STANDARD_MISSING",
        "verification_method": "BIS_CATALOGUE",
        "evidence_source": "BIS Catalogue / MED 12",
        "evidence_reference": "IS 14164:2008 Clause 1; IS 8183:1993 Clause 1",
        "evidence_snippet": "IS 14164 specifies methods for securing and weather-proofing thermal insulation on pipes, valves and pumps. IS 8183 specifies preformed mineral wool insulation material.",
        "reasoning": "Insulation of chilled or hot water hospital pumps and piping prevents condensation and heat loss. IS 14164 is the primary national code of practice governing application and cladding of pipe thermal insulation.",
        "confidence": "High",
        "human_verified": "FALSE",
        "reviewer_notes": "Aluminum sheet cladding (IS 737) is conventionally applied over mineral wool or elastomeric foam in hospital plant rooms."
    },
    {
        "tender_id": "T014",
        "requirement_id": "T014-R002",
        "requirement_text": "commissioning of three numbers of Process Water Pump motors 3.3 kV",
        "category": "product_equipment",
        "source_page": 1,
        "explicit_standard": "",
        "applicable_standard": "IS/IEC 60034-1 : 2017; IS 5120 : 1977",
        "standard_title": "Rotating electrical machines - Part 1: Rating and performance; Technical requirements for rotodynamic special purpose pumps",
        "standard_status": "Active",
        "verification_outcome": "STANDARD_MISSING",
        "verification_method": "BIS_CATALOGUE",
        "evidence_source": "BIS Catalogue / ETD 15 (Rotating Machines) & MED 20 (Pumps)",
        "evidence_reference": "IS/IEC 60034-1 Clause 1 Scope; IS 5120 Clause 1",
        "evidence_snippet": "IS/IEC 60034-1 governs high-voltage/medium-voltage (3.3 kV) rotating electric motors, temperature rise, and insulation class. IS 5120 covers special purpose industrial process pumps.",
        "reasoning": "BARC Trombay specifies 3 numbers of 3.3 kV Process Water Pump motors. Medium-voltage heavy motors must comply with IS/IEC 60034-1, while process pump hydraulics and casings follow IS 5120.",
        "confidence": "High",
        "human_verified": "FALSE",
        "reviewer_notes": "General agricultural pump standards (such as IS 9694) are rejected because this is an industrial 3.3 kV nuclear process cooling water system."
    },
    {
        "tender_id": "T020",
        "requirement_id": "T020-R001",
        "requirement_text": "Repair/ maint of CPVC pipe in lieu of rusted GI pipe at Laitumkhrah Grn",
        "category": "material",
        "source_page": 1,
        "explicit_standard": "",
        "applicable_standard": "IS 15778 : 2007; IS 1239 (Part 1) : 2004",
        "standard_title": "Chlorinated Polyvinyl Chloride (CPVC) Pipes for Potable Hot and Cold Water Supplies - Specification; Steel Tubes, Tubulars and Other Wrought Steel Fittings",
        "standard_status": "Active",
        "verification_outcome": "STANDARD_MISSING",
        "verification_method": "BIS_CATALOGUE",
        "evidence_source": "BIS Catalogue / CED 50 / CPVC Pipes QCO 2023",
        "evidence_reference": "IS 15778:2007 Clause 1 Scope; IS 1239 (Part 1) Clause 1",
        "evidence_snippet": "IS 15778 specifies chlorinated polyvinyl chloride (CPVC) pipe dimensions (SDR 11 and SDR 13.5), hydrostatic pressure and water potability. Mandatory ISI Mark under CPVC Pipes QCO.",
        "reasoning": "The tender explicitly calls for replacing rusted GI water pipes with CPVC water pipelines. IS 15778 governs CPVC potable water piping and IS 1239 governs the legacy GI piping being replaced.",
        "confidence": "High",
        "human_verified": "FALSE",
        "reviewer_notes": "Mandatory ISI Mark certification under CPVC Pipes Quality Control Order 2023. UPVC under IS 4985 is rejected because CPVC was explicitly mandated."
    }
]

fields = [
    'tender_id',
    'requirement_id',
    'requirement_text',
    'category',
    'source_page',
    'explicit_standard',
    'applicable_standard',
    'standard_title',
    'standard_status',
    'verification_outcome',
    'verification_method',
    'evidence_source',
    'evidence_reference',
    'evidence_snippet',
    'reasoning',
    'confidence',
    'human_verified',
    'reviewer_notes'
]

with open('dataset/ground_truth/ground_truth.csv', 'w', newline='', encoding='utf-8') as f:
    writer = csv.DictWriter(f, fieldnames=fields)
    writer.writeheader()
    writer.writerows(ground_truth_rows)

print(f'Successfully updated ground_truth.csv with {len(ground_truth_rows)} rows and all required verification fields.')
