"""
Module: src/ai_understanding.py
Purpose: AI Requirement Understanding layer for TenderSaathi.

Converts natural-language tender requirements into strict structured technical fields:
- equipment: List[str]
- control: List[str]
- electrical: List[str]
- voltage: List[str]
- application: List[str]
- work_type: List[str]

CRITICAL SAFETY BOUNDARY:
- The LLM MUST NOT select, invent, validate, or declare any IS standard applicable.
- The LLM MUST NOT generate evidence, lifecycle status, BIS relationships, or compliance decisions.
- Any standard citations or IS numbers produced by the LLM are stripped and ignored.
- If the LLM is disabled, unavailable, times out, or produces malformed output,
  the system automatically falls back to deterministic requirement decomposition.
"""

import os
import json
import re
import urllib.request
import urllib.error
from dataclasses import dataclass, field, asdict
from typing import List, Dict, Any, Optional

try:
    from dotenv import load_dotenv
    load_dotenv()
except ImportError:
    pass

from src.decompose import CompoundRequirementDecomposer, RequirementComponent, DecompositionResult


# Regex pattern to detect and strip any IS numbers inadvertently generated by an LLM
IS_CODE_PATTERN = re.compile(r'\b(?:IS|IS/ISO|IS/IEC|SP)\s*(?:/|\s*)?\d+(?:\s*(?:Part|Sec)\s*\d+)*(?:\s*\(Part\s*\d+\))?', re.IGNORECASE)



@dataclass
class ParsedRequirement:
    """Strict structured representation of a natural language requirement."""
    equipment: List[str] = field(default_factory=list)
    control: List[str] = field(default_factory=list)
    electrical: List[str] = field(default_factory=list)
    voltage: List[str] = field(default_factory=list)
    application: List[str] = field(default_factory=list)
    work_type: List[str] = field(default_factory=list)
    ai_provider: str = "deterministic"
    ai_model: Optional[str] = None
    is_fallback: bool = True
    raw_response: Optional[str] = None

    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)

    def to_components(self) -> List[RequirementComponent]:
        """Converts structured facets into RequirementComponent objects for retrieval."""
        components = []
        for eq in self.equipment:
            if eq.strip():
                components.append(RequirementComponent(
                    text=eq.strip(),
                    component_type="equipment",
                    domain="mechanical",
                    extracted_attributes={"domain": "mechanical"}
                ))
        for ctrl in self.control:
            if ctrl.strip():
                components.append(RequirementComponent(
                    text=ctrl.strip(),
                    component_type="control",
                    domain="control",
                    extracted_attributes={"domain": "control"}
                ))
        for el in self.electrical:
            if el.strip():
                components.append(RequirementComponent(
                    text=el.strip(),
                    component_type="electrical",
                    domain="electrical",
                    extracted_attributes={"domain": "electrical"}
                ))
        for v in self.voltage:
            if v.strip():
                components.append(RequirementComponent(
                    text=v.strip(),
                    component_type="electrical",
                    domain="electrical",
                    extracted_attributes={"level": "medium_or_high_voltage" if any(k in v.lower() for k in ["kv", "3.3", "6.6", "11", "33"]) else "low_voltage"}
                ))
        for app in self.application:
            if app.strip():
                components.append(RequirementComponent(
                    text=app.strip(),
                    component_type="application",
                    domain="mechanical",
                    extracted_attributes={"is_process": "process" in app.lower()}
                ))
        for wt in self.work_type:
            if wt.strip():
                components.append(RequirementComponent(
                    text=wt.strip(),
                    component_type="action",
                    domain="general",
                    extracted_attributes={}
                ))
        return components


SYSTEM_PROMPT = """You are a technical requirement decomposition engine for Indian public procurement.
Your ONLY role is to convert natural-language tender requirements into structured technical fields.

You must respond ONLY with a valid JSON object adhering strictly to this schema:
{
  "equipment": ["item1", "item2"],
  "control": ["control_gear1"],
  "electrical": ["electrical_component1"],
  "voltage": ["voltage_rating"],
  "application": ["use_case_or_medium"],
  "work_type": ["supply", "installation", "testing"]
}

STRICT CONSTRAINTS:
1. Every field MUST be a list of strings. Empty lists [] are allowed.
2. DO NOT include Indian Standard (IS) numbers or any standard codes.
3. DO NOT recommend, invent, or mention any standard numbers.
4. DO NOT make compliance, quality, or legal determinations.
5. Return ONLY valid JSON, with no introductory or concluding text.
"""


class AIRequirementParser:
    """
    Parses procurement specifications using Groq LLM (or OpenRouter if explicitly configured)
    with strict JSON validation, standard-code stripping, and automatic deterministic fallback.
    """

    def __init__(
        self,
        enabled: Optional[bool] = None,
        provider: Optional[str] = None,
        model: Optional[str] = None,
        api_key: Optional[str] = None,
        timeout: float = 8.0
    ):
        env_enabled = os.getenv("TENDERSAATHI_LLM_ENABLED", "false").lower() in ("true", "1", "yes")
        self.enabled = env_enabled if enabled is None else enabled
        self.provider = (provider or os.getenv("TENDERSAATHI_LLM_PROVIDER", "groq")).lower()
        self.model = model or os.getenv("TENDERSAATHI_LLM_MODEL", "openai/gpt-oss-120b")
        self.timeout = timeout

        # API keys (never logged or exposed)
        if api_key is not None:
            self._api_key = api_key.strip()
        elif self.provider == "groq":
            self._api_key = os.getenv("GROQ_API_KEY", "").strip()
        elif self.provider == "openrouter":
            self._api_key = os.getenv("OPENROUTER_API_KEY", "").strip()
        else:
            self._api_key = os.getenv("LLM_API_KEY", "").strip()

        self.decomposer = CompoundRequirementDecomposer()

    def parse(self, text: str) -> ParsedRequirement:
        """
        Parses requirement text. Returns ParsedRequirement.
        If LLM is disabled, missing key, fails, or produces invalid output,
        automatically falls back to deterministic decomposition.
        """
        text_clean = text.strip()
        if not text_clean:
            return ParsedRequirement(
                ai_provider="deterministic",
                ai_model=None,
                is_fallback=True
            )

        if not self.enabled or not self._api_key:
            return self._fallback_decompose(text_clean, reason="LLM disabled or missing API key")

        try:
            raw_response = self._call_llm_api(text_clean)
            parsed_json = self._validate_and_sanitize_response(raw_response)
            if parsed_json is not None:
                return ParsedRequirement(
                    equipment=parsed_json["equipment"],
                    control=parsed_json["control"],
                    electrical=parsed_json["electrical"],
                    voltage=parsed_json["voltage"],
                    application=parsed_json["application"],
                    work_type=parsed_json["work_type"],
                    ai_provider=self.provider,
                    ai_model=self.model,
                    is_fallback=False,
                    raw_response=raw_response
                )
        except Exception:
            # Any network error, timeout, or unexpected exception falls back cleanly
            pass

        return self._fallback_decompose(text_clean, reason="API error or invalid schema")

    def _call_llm_api(self, text: str) -> str:
        """Invokes the configured LLM API (Groq or OpenRouter)."""
        if not self._api_key:
            raise ValueError(f"{self.provider.capitalize()} API key not configured")

        if self.provider == "groq":
            url = "https://api.groq.com/openai/v1/chat/completions"
        elif self.provider == "openrouter":
            url = "https://openrouter.ai/api/v1/chat/completions"
        else:
            raise ValueError(f"Unsupported LLM provider: {self.provider}")

        payload = {
            "model": self.model,
            "messages": [
                {"role": "system", "content": SYSTEM_PROMPT},
                {"role": "user", "content": f"Requirement: {text}"}
            ],
            "temperature": 0.0,
            "response_format": {"type": "json_object"}
        }

        data = json.dumps(payload).encode("utf-8")
        headers = {
            "Authorization": f"Bearer {self._api_key}",
            "Content-Type": "application/json",
            "User-Agent": "TenderSaathi-AI/1.0"
        }

        req = urllib.request.Request(url, data=data, headers=headers)
        try:
            with urllib.request.urlopen(req, timeout=self.timeout) as resp:
                body = resp.read().decode("utf-8")
                res_obj = json.loads(body)
                return res_obj["choices"][0]["message"]["content"]
        except urllib.error.HTTPError as e:
            # Mask all headers and secrets from any error representation
            raise RuntimeError(f"{self.provider.capitalize()} API request failed with HTTP status {e.code}") from None
        except Exception:
            raise RuntimeError(f"{self.provider.capitalize()} API request failed") from None


    def _validate_and_sanitize_response(self, raw_content: str) -> Optional[Dict[str, List[str]]]:
        """
        Validates output against strict JSON schema.
        Rejects non-lists, missing keys, and strips any attempted IS standard citations.
        """
        if not raw_content or not isinstance(raw_content, str):
            return None

        # Clean potential markdown fences
        cleaned = raw_content.strip()
        if cleaned.startswith("```"):
            cleaned = re.sub(r"^```(?:json)?\s*", "", cleaned)
            cleaned = re.sub(r"\s*```$", "", cleaned)

        try:
            data = json.loads(cleaned)
        except Exception:
            return None

        if not isinstance(data, dict):
            return None

        required_keys = ["equipment", "control", "electrical", "voltage", "application", "work_type"]
        sanitized: Dict[str, List[str]] = {}

        for k in required_keys:
            if k not in data:
                return None
            val = data[k]
            # If string was provided instead of list, convert to single-element list if non-empty
            if isinstance(val, str):
                val = [val.strip()] if val.strip() else []
            elif not isinstance(val, list):
                return None

            cleaned_items = []
            for item in val:
                if not isinstance(item, str):
                    continue
                item_str = item.strip()
                if not item_str:
                    continue
                # CRITICAL SAFETY BOUNDARY: Strip any IS code numbers from values
                item_stripped = IS_CODE_PATTERN.sub("", item_str).strip(" ,;:-")
                if item_stripped:
                    cleaned_items.append(item_stripped)
            sanitized[k] = cleaned_items

        return sanitized

    def _fallback_decompose(self, text: str, reason: str = "") -> ParsedRequirement:
        """Falls back deterministically to existing CompoundRequirementDecomposer."""
        decomp: DecompositionResult = self.decomposer.decompose(text)

        equipment = []
        control = []
        electrical = []
        voltage = []
        application = []
        work_type = []

        for c in decomp.components:
            txt = c.text
            ctype = c.component_type
            if ctype in ("equipment", "product", "material"):
                equipment.append(txt)
            elif ctype == "control":
                control.append(txt)
            elif ctype == "electrical":
                electrical.append(txt)
                if c.extracted_attributes.get("level") == "medium_or_high_voltage":
                    voltage.append("medium_or_high_voltage")
            elif ctype == "application":
                application.append(txt)
            elif ctype == "action":
                work_type.append(txt)

        return ParsedRequirement(
            equipment=equipment,
            control=control,
            electrical=electrical,
            voltage=voltage,
            application=application,
            work_type=work_type,
            ai_provider="deterministic",
            ai_model=None,
            is_fallback=True,
            raw_response=None
        )
